"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-07-22 18:36:21.923552
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Releases before Alembic created tables directly with SQLAlchemy. Adopt an
    # existing installation without dropping data, while filling in tables that
    # may have been introduced by a later pre-migration release.
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names()) - {"alembic_version"}
    if existing_tables:
        from app import models  # noqa: F401
        from app.core.db import Base

        Base.metadata.create_all(bind=bind, checkfirst=True)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=128), nullable=True),
    sa.Column('topology', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reproduction_steps', sa.Text(), nullable=True),
    sa.Column('issue_time', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('knowledge_categories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_categories_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('firmware_range', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('trust_level', sa.String(length=16), nullable=False),
    sa.Column('confidentiality', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_source_type'), ['source_type'], unique=False)

    op.create_table('model_profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=512), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=True),
    sa.Column('api_key_hint', sa.String(length=32), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_profiles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_profiles_task_type'), ['task_type'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_case_id'), ['case_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('knowledge_document_categories',
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('knowledge_document_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_document_categories_category_id'), ['category_id'], unique=False)

    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('chunk_id', sa.String(length=40), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['model_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'profile_id', name='uq_knowledge_embedding_profile')
    )
    with op.batch_alter_table('knowledge_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_embeddings_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_embeddings_profile_id'), ['profile_id'], unique=False)

    op.create_table('log_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('timestamp_raw', sa.String(length=128), nullable=True),
    sa.Column('timestamp_normalized', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('component', sa.String(length=128), nullable=False),
    sa.Column('event_code', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('entities_json', sa.Text(), nullable=False),
    sa.Column('parser_id', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_events_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_event_code'), ['event_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_events_timestamp_normalized'), ['timestamp_normalized'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=40), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_case_id'), ['case_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_case_id'), ['case_id'], unique=False)

    op.create_table('code_symbols',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('repository_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=True),
    sa.Column('calls_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_symbols_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_repository_id'), ['repository_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_symbols_repository_id'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_name'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_module'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_kind'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_file_path'))

    op.drop_table('code_symbols')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_case_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_artifact_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_case_id'))
        batch_op.drop_index(batch_op.f('ix_reports_analysis_run_id'))

    op.drop_table('reports')
    with op.batch_alter_table('log_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_events_timestamp_normalized'))
        batch_op.drop_index(batch_op.f('ix_log_events_module'))
        batch_op.drop_index(batch_op.f('ix_log_events_level'))
        batch_op.drop_index(batch_op.f('ix_log_events_event_code'))
        batch_op.drop_index(batch_op.f('ix_log_events_component'))
        batch_op.drop_index(batch_op.f('ix_log_events_case_id'))
        batch_op.drop_index(batch_op.f('ix_log_events_artifact_id'))

    op.drop_table('log_events')
    with op.batch_alter_table('knowledge_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_embeddings_profile_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_embeddings_chunk_id'))

    op.drop_table('knowledge_embeddings')
    with op.batch_alter_table('knowledge_document_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_categories_category_id'))

    op.drop_table('knowledge_document_categories')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_case_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifacts_case_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_case_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('model_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_profiles_task_type'))
        batch_op.drop_index(batch_op.f('ix_model_profiles_is_active'))

    op.drop_table('model_profiles')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_module'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_device_type'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('knowledge_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_categories_parent_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_categories_code'))

    op.drop_table('knowledge_categories')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))

    op.drop_table('jobs')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))

    op.drop_table('cases')
    # ### end Alembic commands ###
